{
  "$schema": "http://cyclonedx.org/schema/bom-1.6.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.6",
  "serialNumber": "urn:uuid:0170e3a7-2eb9-412c-8880-02baf9c5af43",
  "version": 1,
  "metadata": {
    "timestamp": "2024-09-19T20:28:12+00:00",
    "tools": {
      "components": [
        {
          "type": "application",
          "group": "aquasecurity",
          "name": "trivy",
          "version": "0.55.2"
        }
      ]
    },
    "component": {
      "bom-ref": "bdadc7aa-0368-4863-abbf-1c9b2ea7b981",
      "type": "application",
      "name": "allegroapp-data-store",
      "properties": [
        {
          "name": "allegroapp-data-store",
          "value": "2"
        }
      ]
    }
  },
  "components": [
    {
      "bom-ref": "pkg:pypi/jinja2@2.4.1",
      "type": "library",
      "name": "jinja2",
      "version": "2.4.1",
      "purl": "pkg:pypi/jinja2@2.4.1",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "pip"
        }
      ]
    },
    {
      "bom-ref": "pkg:pypi/numpy@1.10.3",
      "type": "library",
      "name": "numpy",
      "version": "1.10.3",
      "purl": "pkg:pypi/numpy@1.10.3",
      "properties": [
        {
          "name": "aquasecurity:trivy:PkgType",
          "value": "pip"
        }
      ]
    }
  ],
  "dependencies": [
    {
      "ref": "bdadc7aa-0368-4863-abbf-1c9b2ea7b981",
      "dependsOn": [
        "d6c3d3a1-bd6d-4e80-8015-afe1c61bce55"
      ]
    },
    {
      "ref": "d6c3d3a1-bd6d-4e80-8015-afe1c61bce55",
      "dependsOn": [
        "pkg:pypi/distlib@0.3.4",
        "pkg:pypi/filelock@3.6.0",
        "pkg:pypi/flask@3.0.0",
        "pkg:pypi/jinja2@2.4.1",
        "pkg:pypi/numpy@1.10.3",
        "pkg:pypi/pandas-numpy@8.19.3",
        "pkg:pypi/platformdirs@2.5.1",
        "pkg:pypi/six@1.16.0"
      ]
    },
    {
      "ref": "pkg:pypi/distlib@0.3.4",
      "dependsOn": []
    },
    {
      "ref": "pkg:pypi/filelock@3.6.0",
      "dependsOn": []
    },
    {
      "ref": "pkg:pypi/flask@3.0.0",
      "dependsOn": []
    },
    {
      "ref": "pkg:pypi/jinja2@2.4.1",
      "dependsOn": []
    },
    {
      "ref": "pkg:pypi/numpy@1.10.3",
      "dependsOn": []
    },
    {
      "ref": "pkg:pypi/pandas-numpy@8.19.3",
      "dependsOn": []
    },
    {
      "ref": "pkg:pypi/platformdirs@2.5.1",
      "dependsOn": []
    },
    {
      "ref": "pkg:pypi/six@1.16.0",
      "dependsOn": []
    }
  ],
  "vulnerabilities": [
    {
      "id": "CVE-2014-0012",
      "source": {
        "name": "ghsa",
        "url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "ratings": [
        {
          "source": {
            "name": "ghsa"
          },
          "severity": "medium"
        },
        {
          "source": {
            "name": "nvd"
          },
          "score": 4.4,
          "severity": "medium",
          "method": "CVSSv2",
          "vector": "AV:L/AC:M/Au:N/C:P/I:P/A:P"
        },
        {
          "source": {
            "name": "redhat"
          },
          "score": 4.4,
          "severity": "medium",
          "method": "CVSSv2",
          "vector": "AV:L/AC:M/Au:N/C:P/I:P/A:P"
        },
        {
          "source": {
            "name": "ubuntu"
          },
          "severity": "medium"
        }
      ],
      "cwes": [
        264
      ],
      "description": "FileSystemBytecodeCache in Jinja2 2.7.2 does not properly create temporary directories, which allows local users to gain privileges by pre-creating a temporary directory with a user's uid.  NOTE: this vulnerability exists because of an incomplete fix for CVE-2014-1402.",
      "recommendation": "Upgrade jinja2 to version 2.7.2",
      "advisories": [
        {
          "url": "https://avd.aquasec.com/nvd/cve-2014-0012"
        },
        {
          "url": "http://seclists.org/oss-sec/2014/q1/73"
        },
        {
          "url": "http://secunia.com/advisories/56328"
        },
        {
          "url": "http://secunia.com/advisories/60738"
        },
        {
          "url": "http://www.gentoo.org/security/en/glsa/glsa-201408-13.xml"
        },
        {
          "url": "https://access.redhat.com/security/cve/CVE-2014-0012"
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1051421"
        },
        {
          "url": "https://github.com/mitsuhiko/jinja2/commit/acb672b6a179567632e032f547582f30fa2f4aa7"
        },
        {
          "url": "https://github.com/mitsuhiko/jinja2/pull/292"
        },
        {
          "url": "https://github.com/mitsuhiko/jinja2/pull/296"
        },
        {
          "url": "https://github.com/pallets/jinja/commit/acb672b6a179567632e032f547582f30fa2f4aa7"
        },
        {
          "url": "https://github.com/pallets/jinja2"
        },
        {
          "url": "https://github.com/pallets/jinja2/pull/292"
        },
        {
          "url": "https://github.com/pallets/jinja2/pull/296"
        },
        {
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2014-0012"
        },
        {
          "url": "https://ubuntu.com/security/notices/USN-2301-1"
        },
        {
          "url": "https://www.cve.org/CVERecord?id=CVE-2014-0012"
        }
      ],
      "published": "2014-05-19T14:55:10+00:00",
      "updated": "2023-11-07T02:18:04+00:00",
      "affects": [
        {
          "ref": "pkg:pypi/jinja2@2.4.1",
          "versions": [
            {
              "version": "2.4.1",
              "status": "affected"
            }
          ]
        }
      ]
    },
    {
      "id": "CVE-2017-12852",
      "source": {
        "name": "ghsa",
        "url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
      },
      "ratings": [
        {
          "source": {
            "name": "ghsa"
          },
          "score": 7.5,
          "severity": "high",
          "method": "CVSSv3",
          "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        },
        {
          "source": {
            "name": "nvd"
          },
          "score": 5,
          "severity": "medium",
          "method": "CVSSv2",
          "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
        },
        {
          "source": {
            "name": "nvd"
          },
          "score": 7.5,
          "severity": "high",
          "method": "CVSSv3",
          "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        },
        {
          "source": {
            "name": "photon"
          },
          "severity": "high"
        },
        {
          "source": {
            "name": "redhat"
          },
          "score": 4,
          "severity": "low",
          "method": "CVSSv3",
          "vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
        },
        {
          "source": {
            "name": "ubuntu"
          },
          "severity": "low"
        }
      ],
      "cwes": [
        835
      ],
      "description": "The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack.",
      "recommendation": "Upgrade numpy to version 1.13.3",
      "advisories": [
        {
          "url": "https://avd.aquasec.com/nvd/cve-2017-12852"
        },
        {
          "url": "https://access.redhat.com/security/cve/CVE-2017-12852"
        },
        {
          "url": "https://github.com/BT123/testcasesForMyRequest/tree/master/CVE-2017-12852"
        },
        {
          "url": "https://github.com/advisories/GHSA-frgw-fgh6-9g52"
        },
        {
          "url": "https://github.com/numpy/numpy"
        },
        {
          "url": "https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
        },
        {
          "url": "https://github.com/numpy/numpy/releases/tag/v1.13.3"
        },
        {
          "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2017-1.yaml"
        },
        {
          "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-12852"
        },
        {
          "url": "https://www.cve.org/CVERecord?id=CVE-2017-12852"
        }
      ],
      "published": "2017-08-15T16:29:00+00:00",
      "updated": "2019-10-03T00:03:26+00:00",
      "affects": [
        {
          "ref": "pkg:pypi/numpy@1.10.3",
          "versions": [
            {
              "version": "1.10.3",
              "status": "affected"
            }
          ]
        }
      ]
    }
  ]
}